import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta charSet="utf-8" />
        <title>Compass- The AI powered security for your digital assets.</title>
        <meta
          content="Your business runs on digital assets — we safeguard them. From social media accounts to wallet addresses, we keep your digital presence secure and help you recover fast when things go wrong."
          name="description"
        />
        <meta
          content="Compass- The AI powered security for your digital assets."
          property="og:title"
        />
        <meta
          content="Your business runs on digital assets — we safeguard them. From social media accounts to wallet addresses, we keep your digital presence secure and help you recover fast when things go wrong."
          property="og:description"
        />
        <meta
          content="https://cdn.prod.website-files.com/68c06f93ac6a25b975a866fd/68c13f0776ed5ac52e18f0c0_e750c4a89bb97f9e5a96777e5e5e4827_OG.jpg"
          property="og:image"
        />
        <meta
          content="Compass- The AI powered security for your digital assets."
          property="twitter:title"
        />
        <meta
          content="Your business runs on digital assets — we safeguard them. From social media accounts to wallet addresses, we keep your digital presence secure and help you recover fast when things go wrong."
          property="twitter:description"
        />
        <meta property="og:type" content="website" />
        <meta content="summary_large_image" name="twitter:card" />
        <meta content="width=device-width, initial-scale=1" name="viewport" />
        <meta content="Webflow" name="generator" />
        <link
          href="https://cdn.prod.website-files.com/68c06f93ac6a25b975a866fd/css/bluewave-template.webflow.shared.e5c8cd03b.css"
          rel="stylesheet"
          type="text/css"
        />
        <script
          type="text/javascript"
          dangerouslySetInnerHTML={{
            __html: `
              !function(o, c) {
                var n = c.documentElement, t = " w-mod-";
                n.className += t + "js";
                ("ontouchstart"in o || o.DocumentTouch && c instanceof DocumentTouch) && (n.className += t + "touch")
              }(window, document);
            `,
          }}
        />
        <link
          href="https://cdn.prod.website-files.com/68c06f93ac6a25b975a866fd/68c12aac109f56bcfbb41335_32.svg"
          rel="shortcut icon"
          type="image/x-icon"
        />
        <link
          href="https://cdn.prod.website-files.com/68c06f93ac6a25b975a866fd/68c12aaebe242750baef2b35_256.svg"
          rel="apple-touch-icon"
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
        <script
          src="https://d3e54v103j8qbb.cloudfront.net/js/jquery-3.5.1.min.dc5e7f18c8.js?site=68c06f93ac6a25b975a866fd"
          type="text/javascript"
          integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0="
          crossOrigin="anonymous"
        ></script>
        <script
          src="https://cdn.prod.website-files.com/68c06f93ac6a25b975a866fd/js/webflow.schunk.36b8fb49256177c8.js"
          type="text/javascript"
        ></script>
        <script
          src="https://cdn.prod.website-files.com/68c06f93ac6a25b975a866fd/js/webflow.schunk.5d615211afe87728.js"
          type="text/javascript"
        ></script>
        <script
          src="https://cdn.prod.website-files.com/68c06f93ac6a25b975a866fd/js/webflow.e99c8149.f3fb9be7396fe67b.js"
          type="text/javascript"
        ></script>
        <script
          src="https://cdn.prod.website-files.com/gsap/3.13.0/gsap.min.js"
          type="text/javascript"
        ></script>
        <script
          src="https://cdn.prod.website-files.com/gsap/3.13.0/ScrollTrigger.min.js"
          type="text/javascript"
        ></script>
        <link
          rel="stylesheet"
          href="https://unpkg.com/lenis@1.2.3/dist/lenis.css"
        />
        <script src="https://unpkg.com/lenis@1.2.3/dist/lenis.min.js"></script>
        <script
          dangerouslySetInnerHTML={{
            __html: `
              let lenis = new Lenis({
                lerp: 0.1,
                wheelMultiplier: 0.7,
                gestureOrientation: "vertical",
                normalizeWheel: false,
                smoothTouch: false,
              });

              function raf(time) {
                lenis.raf(time);
                requestAnimationFrame(raf);
              }

              requestAnimationFrame(raf);
            `,
          }}
        />
      </body>
    </html>
  );
}
